require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SlipPaymentsController do

  # This should return the minimal set of attributes required to create a valid
  # SlipPayment. As you add validations to SlipPayment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "amount" => "9.99" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SlipPaymentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all slip_payments as @slip_payments" do
      slip_payment = SlipPayment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:slip_payments).should eq([slip_payment])
    end
  end

  describe "GET show" do
    it "assigns the requested slip_payment as @slip_payment" do
      slip_payment = SlipPayment.create! valid_attributes
      get :show, {:id => slip_payment.to_param}, valid_session
      assigns(:slip_payment).should eq(slip_payment)
    end
  end

  describe "GET new" do
    it "assigns a new slip_payment as @slip_payment" do
      get :new, {}, valid_session
      assigns(:slip_payment).should be_a_new(SlipPayment)
    end
  end

  describe "GET edit" do
    it "assigns the requested slip_payment as @slip_payment" do
      slip_payment = SlipPayment.create! valid_attributes
      get :edit, {:id => slip_payment.to_param}, valid_session
      assigns(:slip_payment).should eq(slip_payment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SlipPayment" do
        expect {
          post :create, {:slip_payment => valid_attributes}, valid_session
        }.to change(SlipPayment, :count).by(1)
      end

      it "assigns a newly created slip_payment as @slip_payment" do
        post :create, {:slip_payment => valid_attributes}, valid_session
        assigns(:slip_payment).should be_a(SlipPayment)
        assigns(:slip_payment).should be_persisted
      end

      it "redirects to the created slip_payment" do
        post :create, {:slip_payment => valid_attributes}, valid_session
        response.should redirect_to(SlipPayment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved slip_payment as @slip_payment" do
        # Trigger the behavior that occurs when invalid params are submitted
        SlipPayment.any_instance.stub(:save).and_return(false)
        post :create, {:slip_payment => { "amount" => "invalid value" }}, valid_session
        assigns(:slip_payment).should be_a_new(SlipPayment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SlipPayment.any_instance.stub(:save).and_return(false)
        post :create, {:slip_payment => { "amount" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested slip_payment" do
        slip_payment = SlipPayment.create! valid_attributes
        # Assuming there are no other slip_payments in the database, this
        # specifies that the SlipPayment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SlipPayment.any_instance.should_receive(:update_attributes).with({ "amount" => "9.99" })
        put :update, {:id => slip_payment.to_param, :slip_payment => { "amount" => "9.99" }}, valid_session
      end

      it "assigns the requested slip_payment as @slip_payment" do
        slip_payment = SlipPayment.create! valid_attributes
        put :update, {:id => slip_payment.to_param, :slip_payment => valid_attributes}, valid_session
        assigns(:slip_payment).should eq(slip_payment)
      end

      it "redirects to the slip_payment" do
        slip_payment = SlipPayment.create! valid_attributes
        put :update, {:id => slip_payment.to_param, :slip_payment => valid_attributes}, valid_session
        response.should redirect_to(slip_payment)
      end
    end

    describe "with invalid params" do
      it "assigns the slip_payment as @slip_payment" do
        slip_payment = SlipPayment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SlipPayment.any_instance.stub(:save).and_return(false)
        put :update, {:id => slip_payment.to_param, :slip_payment => { "amount" => "invalid value" }}, valid_session
        assigns(:slip_payment).should eq(slip_payment)
      end

      it "re-renders the 'edit' template" do
        slip_payment = SlipPayment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SlipPayment.any_instance.stub(:save).and_return(false)
        put :update, {:id => slip_payment.to_param, :slip_payment => { "amount" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested slip_payment" do
      slip_payment = SlipPayment.create! valid_attributes
      expect {
        delete :destroy, {:id => slip_payment.to_param}, valid_session
      }.to change(SlipPayment, :count).by(-1)
    end

    it "redirects to the slip_payments list" do
      slip_payment = SlipPayment.create! valid_attributes
      delete :destroy, {:id => slip_payment.to_param}, valid_session
      response.should redirect_to(slip_payments_url)
    end
  end

end
